FROM python:3.8.13-slim-buster

WORKDIR /app

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set install.trusted-host mirrors.aliyun.com,pypi.tuna.tsinghua.edu.cn

RUN pip install mlflow>=1.0 psycopg2-binary boto3
