# For more information, please refer to https://aka.ms/vscode-docker-python
FROM apache/airflow:2.3.3-python3.8
#  my-awesome-apt-dependency-to-add \
USER root
# COPY scripts/sources.list  /etc/apt/sources.list
RUN printf "deb http://mirrors.163.com/debian/ buster main non-free contrib\ndeb http://mirrors.163.com/debian/ buster-updates main non-free contrib\ndeb http://mirrors.163.com/debian/ buster-backports main non-free contrib\ndeb http://mirrors.163.com/debian-security/ buster/updates main non-free contrib\ndeb-src http://mirrors.163.com/debian/ buster main non-free contrib\ndeb-src http://mirrors.163.com/debian/ buster-updates main non-free contrib\ndeb-src http://mirrors.163.com/debian/ buster-backports main non-free contrib\ndeb-src http://mirrors.163.com/debian-security/ buster/updates main non-free contrib" > /etc/apt/sources.list
# 安装解压工具
RUN apt-get update && \
    apt-get install -yq unzip

ENV AIRFLOW_UID=50000
ENV AIRFLOW_GID=0

USER airflow

EXPOSE 8080

WORKDIR /app

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set install.trusted-host mirrors.aliyun.com,pypi.tuna.tsinghua.edu.cn
RUN python -m pip install --user torch==1.12.1

COPY ./requirements.txt ./requirements.txt
RUN python -m pip install --user -r ./requirements.txt
# fix: Fix compatibility with Werkzeug 2.2 and Flask 2.2.
# https://github.com/maxcountryman/flask-login/blob/main/CHANGES.md#version-062
RUN python -m pip install --user flask-login>=0.6.2
RUN python -m pip install --user werkzeug==2.1.2
